[FilterPlugin]
; Files and folders to include absolutely in the final build
/RestartEditor.uplugin
/README.md
/LICENSE
/Resources/...
/Source/...
/Binaries/...

; Files or folders to exclude from packaging
-.git/...
-.vs/...